FROM oven/bun:1.2.8-slim AS base
WORKDIR /app

FROM base AS install
COPY . .
RUN bun install --frozen-lockfile

FROM install AS build
# SvelteKit $env/static/* values are compiled in at build time.
# On Render, pass these as Docker build args if you need non-empty values in the built image.
ARG AUTH_DATABASE_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NO_REPLY_EMAIL
ARG PUBLIC_SITE_NAME
ARG SES_SMTP_HOST
ARG SES_SMTP_PASS
ARG SES_SMTP_PORT
ARG SES_SMTP_USER
ARG STORAGE_ACCESS_KEY_ID
ARG STORAGE_BUCKET_NAME
ARG STORAGE_ENDPOINT
ARG STORAGE_PUBLIC_URL
ARG STORAGE_SECRET_ACCESS_KEY
ARG TURSO_API_TOKEN
ARG TURSO_GROUP
ARG TURSO_GROUP_AUTH_TOKEN
ARG TURSO_ORGANIZATION
ARG TURSO_PARENT_DB_NAME

ENV AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}
ENV FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
ENV FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV NO_REPLY_EMAIL=${NO_REPLY_EMAIL}
ENV PUBLIC_SITE_NAME=${PUBLIC_SITE_NAME}
ENV SES_SMTP_HOST=${SES_SMTP_HOST}
ENV SES_SMTP_PASS=${SES_SMTP_PASS}
ENV SES_SMTP_PORT=${SES_SMTP_PORT}
ENV SES_SMTP_USER=${SES_SMTP_USER}
ENV STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
ENV STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
ENV STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
ENV STORAGE_PUBLIC_URL=${STORAGE_PUBLIC_URL}
ENV STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
ENV TURSO_API_TOKEN=${TURSO_API_TOKEN}
ENV TURSO_GROUP=${TURSO_GROUP}
ENV TURSO_GROUP_AUTH_TOKEN=${TURSO_GROUP_AUTH_TOKEN}
ENV TURSO_ORGANIZATION=${TURSO_ORGANIZATION}
ENV TURSO_PARENT_DB_NAME=${TURSO_PARENT_DB_NAME}

RUN bun run build

FROM oven/bun:1.2.8-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY --from=build --chown=bun:bun /app/package.json ./package.json
COPY --from=build --chown=bun:bun /app/node_modules ./node_modules
COPY --from=build --chown=bun:bun /app/apps/website/package.json ./apps/website/package.json
COPY --from=build --chown=bun:bun /app/apps/website/build ./apps/website/build
COPY --from=build --chown=bun:bun /app/apps/website/node_modules ./apps/website/node_modules
COPY --from=build --chown=bun:bun /app/packages ./packages

USER bun

EXPOSE 3000

CMD ["bun", "apps/website/build/index.js"]
