FROM oven/bun:1.2-slim AS base
WORKDIR /app
RUN bun install -g pnpm@10.32.0

ARG AUTH_DATABASE_URL
ARG PARENT_DATABASE_URL
ARG TURSO_ORGANIZATION
ARG TURSO_API_TOKEN
ARG TURSO_GROUP_AUTH_TOKEN
ARG TURSO_GROUP
ARG TURSO_PARENT_DB_NAME
ARG GOOGLE_USER
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REFRESH_TOKEN
ARG SES_SMTP_HOST
ARG SES_SMTP_PORT
ARG SES_SMTP_USER
ARG SES_SMTP_PASS
ARG NO_REPLY_EMAIL
ARG BETTER_AUTH_URL
ARG BETTER_AUTH_SECRET
ARG PUBLIC_SITE_NAME
ARG STORAGE_PUBLIC_URL
ARG STORAGE_BUCKET_NAME
ARG STORAGE_ENDPOINT
ARG STORAGE_ACCESS_KEY_ID
ARG STORAGE_SECRET_ACCESS_KEY
ARG AWS_SESSION_TOKEN
ARG S3_SESSION_TOKEN
ARG REPLICATE_API_TOKEN

ENV AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
ENV PARENT_DATABASE_URL=${PARENT_DATABASE_URL}
ENV TURSO_ORGANIZATION=${TURSO_ORGANIZATION}
ENV TURSO_API_TOKEN=${TURSO_API_TOKEN}
ENV TURSO_GROUP_AUTH_TOKEN=${TURSO_GROUP_AUTH_TOKEN}
ENV TURSO_GROUP=${TURSO_GROUP}
ENV TURSO_PARENT_DB_NAME=${TURSO_PARENT_DB_NAME}
ENV GOOGLE_USER=${GOOGLE_USER}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
ENV SES_SMTP_HOST=${SES_SMTP_HOST}
ENV SES_SMTP_PORT=${SES_SMTP_PORT}
ENV SES_SMTP_USER=${SES_SMTP_USER}
ENV SES_SMTP_PASS=${SES_SMTP_PASS}
ENV NO_REPLY_EMAIL=${NO_REPLY_EMAIL}
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ENV PUBLIC_SITE_NAME=${PUBLIC_SITE_NAME}
ENV STORAGE_PUBLIC_URL=${STORAGE_PUBLIC_URL}
ENV STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
ENV STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
ENV STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
ENV STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
ENV AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
ENV S3_SESSION_TOKEN=${S3_SESSION_TOKEN}
ENV REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}

FROM base AS deps
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json turbo.json ./
COPY packages/db/package.json ./packages/db/
COPY packages/auth/package.json ./packages/auth/
COPY packages/config/package.json ./packages/config/
COPY packages/ui/package.json ./packages/ui/
COPY apps/website/package.json ./apps/website/
RUN pnpm install --frozen-lockfile

FROM deps AS builder
COPY . .
RUN bun run build

FROM base AS release
RUN mkdir -p /app && chown -R bun:bun /app
USER bun

COPY --from=builder --chown=bun:bun /app/apps/website/build ./app/apps/website
COPY --from=builder --chown=bun:bun /app/node_modules ./node_modules
COPY --from=builder --chown=bun:bun /app/packages ./packages
COPY --from=builder --chown=bun:bun /app/packages/db/migrations ./migrations

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:3000/health || exit 1

CMD ["bun", "run", "./app/apps/website/index.js"]
