/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1b66ea14499a96fb2fc1fef071629103)
interface __BaseEnv_Env {
	STORAGE: R2Bucket;
	ASSETS: Fetcher;
	PUBLIC_ENVIRONMENT: "development" | "production";
	PUBLIC_SITE_NAME: "stores4u";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface DevEnv {
		STORAGE: R2Bucket;
		ASSETS: Fetcher;
		PUBLIC_ENVIRONMENT: "development";
		PUBLIC_SITE_NAME: "stores4u";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ENVIRONMENT" | "PUBLIC_SITE_NAME">> {}
}
