/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f45ddcd149188b173c6024b391d2cd45)
interface __BaseEnv_Env {
	STORAGE: R2Bucket;
	ASSETS: Fetcher;
	PUBLIC_ENVIRONMENT: "production";
	PUBLIC_SITE_NAME: "Kagom";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ENVIRONMENT" | "PUBLIC_SITE_NAME">> {}
}
